
<!DOCTYPE html>
<html lang="fr">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>My WONDERFULL Website</title>

    <!-- Bootstrap Core CSS -->
    <link href="view/css/bootstrap.min.css" rel="stylesheet" >

    <!-- Custom CSS -->
    <link href="view/css/blog-home.css" rel="stylesheet" >


    <link href="view/css/blog-post.css" rel="stylesheet">


    <!-- une categorie -->
     <link href="view/css/heroic-features.css" rel="stylesheet">

<!slider-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <script type="text/javascript" src="view/js/coin-slider.js"></script>

  <link rel="stylesheet" href="view/css/coin-slider-styles.css" type="text/css" />


<!-- facebook-->
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<!-- google+ -->
<script type="text/javascript">
  window.___gcfg = {lang: 'fr'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>



      <?php if("inscription" == $page):?>

        <link href="view/css/strength.css" rel="stylesheet">

<!-- pinterest-->
<script async defer src="//assets.pinterest.com/js/pinit.js"></script>

    <?php endif;?>

 <style type="text/css">
 .form-signin{
    margin : 0 auto;
    
    max-width: 330px;

 }

 </style>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
 <!-- datepicker -->

  <?php if("ajouterArticle" == $page):?>
        <link rel="stylesheet" href="view/css/jquery-ui.min.css">
        <link href="view/css/jquery-ui.theme.min.css" rel="stylesheet">
    <?php endif;?>

  
</head>

<body>

    <?php include 'navbar.phtml' ?>

    <!-- Page Content -->
    <div class="container">

        <div class="row">