


<!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                
                    <h4>Blog Categories</h4>
                    
                        
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="?page=unecategorie&id_cat=1">Japon</a>
                                </li>
                                <li><a href="?page=unecategorie&id_cat=2">Korea</a>
                                </li>
                                <li><a href="?page=unecategorie&id_cat=3">Test</a>
                                </li>
                                <li><a href="?page=unecategorie&id_cat=4">Design K</a>
                                </li>
                            </ul>
                            </div>
                            <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="?page=unecategorie&id_cat=5">Animation</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                </div> 
                  </div>       
                  
                    
            <div class="well">
        <div class="row">
            <div class="col-lg-12">
                <ul class="list-unstyled">
                    <div id="fb-root">
                        <li>Facebook </li>
                        <li>         
                            <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width="345" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
                        </li>
                    </div>
                </ul>

            </div>
        </div>
        </div>
        
        <div class="well">
        <div class="row">
            <div class="col-lg-12">
                <ul class="list-unstyled">
                    <div id="fb-root">
                        <li>Google +</li>
                        <li>         
                            <div class="g-follow" data-annotation="bubble" data-height="24" data-href="https://plus.google.com/{pageId}" data-rel="author"></div>
                        </li>
                    </div>
                </ul>

            </div>
        </div>
        </div>
    


                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->

<!--
        https://developers.pinterest.com/tools/widget-builder/?tall=true&buttonType=oneImage&count=above

https://developers.facebook.com/docs/plugins/like-button/#configurator

https://developers.google.com/+/web/follow/
    -->