<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>404 Not Found</title>
	<!--style css> -->
  <link href="view/css/bootstrap.min.css" rel="stylesheet" >


  <link href="view/css/style.css" rel="stylesheet" >
	<link href="view/css/styleEa.css" rel="stylesheet" >
	<!--typo-->
	<link href='https://fonts.googleapis.com/css?family=Dancing+Script:700' rel='stylesheet' type='text/css'>

</head>
<body>

	<?php include 'partials/navbar.phtml'; ?>

 <section class="section shamrock">
   <h1>PAGE 404 <span class="shake shake-delay">NOT FOUND !</span></h1>
	</section>

<div id="earth">
<div class="globe">
  <div class="front"></div>
  <div class="mapfront"></div>
  <div class="mapback"></div>
  <div class="back"></div>
</div>
	</div>

<footer div="footerSp">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; My WONDERFULL Website 2016</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>
</body>
</html>
