<?php include "partials/header.phtml"; ?>
	



 <body>

    <div class="container">
    	 

      <form novalidate class="form-signin" method="POST">
      	<h2 class="form-signin-heading">Please sign in</h2>


        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" name ="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <?php 	if(!empty ($errors["inputEmail"]))
			{echo $errors["inputEmail"];  }?>
        
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" name ="inputPassword" class="form-control" placeholder="Password" required>
		<?php 	if(!empty ($errors["inputPassword"]))
			{echo $errors["inputPassword"];  }?>

        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me" name ="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>
	
    </div> <!-- /container -->
<br>
<br>
<br>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>



        <hr>

 <?php include "partials/footer.phtml"; ?>